-- MySQL Script generated by MySQL Workbench
-- Sun Sep 21 13:24:27 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema library
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema library
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `library` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `library` ;

-- -----------------------------------------------------
-- Table `library`.`member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`member` (
  `member_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `phoneNumber` VARCHAR(45) NULL,
  `membershipDate` DATE NULL,
  PRIMARY KEY (`member_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`book` (
  `book_id` INT NOT NULL,
  `member_id` INT NOT NULL,
  `title` VARCHAR(60) NULL,
  `author` VARCHAR(60) NULL,
  `publisher` VARCHAR(45) NULL,
  `copiesAvailable` VARCHAR(45) NULL,
  PRIMARY KEY (`book_id`),
  INDEX `fk_book_member1_idx` (`member_id` ASC) VISIBLE,
  CONSTRAINT `fk_book_member1`
    FOREIGN KEY (`member_id`)
    REFERENCES `library`.`member` (`member_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`librarian`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`librarian` (
  `librarian_id` INT NOT NULL,
  `staffId` VARCHAR(15) NULL,
  `librarianName` VARCHAR(65) NULL,
  `phoneNumber` VARCHAR(45) NULL,
  `dutyDate` VARCHAR(45) NULL,
  PRIMARY KEY (`librarian_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`borrowTransaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`borrowTransaction` (
  `transaction_id` INT NOT NULL,
  `member_id` INT NOT NULL,
  `librarian_id` INT NOT NULL,
  `borrowDate` DATETIME NULL,
  `dueDate` DATE NULL,
  `returnDate` DATE NULL,
  PRIMARY KEY (`transaction_id`),
  INDEX `fk_borrowTransaction_member_idx` (`member_id` ASC) VISIBLE,
  INDEX `fk_borrowTransaction_librarian1_idx` (`librarian_id` ASC) VISIBLE,
  CONSTRAINT `fk_borrowTransaction_member`
    FOREIGN KEY (`member_id`)
    REFERENCES `library`.`member` (`member_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_borrowTransaction_librarian1`
    FOREIGN KEY (`librarian_id`)
    REFERENCES `library`.`librarian` (`librarian_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
